name: labz infra deployment

env:
  BASE_TERRAFORM_DIR: "terraform"
  INFRA_SERVICE: "sql-dbs"
  ENVIRONMENT: dev
  TF_VARS_vsphere_password: "${{ secrets.VSPHERE_PASSWORD }}"
  TF_VARS_vsphere_server: "${{ secrets.VSPHERE_PASSWORD }}"
  TF_VARS_vm_network_name: "${{ secrets.VSPHERE_PASSWORD }}"


on:
  push:
    branches:
      - dev
    # paths:
    #   - "${{ BASE_TERRAFORM_DIR }}/${{ INFRA_SERVICE }}"

jobs:
  dev_plan:
    runs-on: 
      group: Default
      labels: [ self-hosted, linux, ]
    defaults:
      run:
        working-directory: "${{ env.BASE_TERRAFORM_DIR }}/${{ env.INFRA_SERVICE }}"
    name: terraform plan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file ${{ env.ENVIRONMENT }}.tfvars



